### ISSUE TITLE
Growing buffer validation error upon adding many conducting equipment in a big project

### ISSUE THREAD

**Issue by arulrajirudayasamy** [openscd/open-scd#1259] opened 2023-05-12 12:15 UTC
**Describe the bug**
Upon adding many conducting equipment in the project leads to growing buffer validation error in OpenSCD version 0.31.0

**To Reproduce**
1. Import .scd file that is larger than the size of 45MB.
2. Add minimum of three conducting equipment's (one CB and two disconnectors for example) for more than two bays in a project.
3. Growing buffer validation error upon adding many conducting equipment in the project
4. See error below in the attachments

**Expected behavior**
There should be ho validation errors 

**Screenshots**
![image](https://github.com/openscd/open-scd/assets/97508332/f5c7fd8a-83ef-441b-84ed-93829757e28b)

**Desktop (please complete the following information):**
 - OS: [e.g. Microsoft Windows 10 Enterprise
 - Browser [\Microsoft Edge)
 - Version [Version 113.0.1774.35 (Official build) (64-bit]

**Additional context**

**Comment by Sander3003** [comment] 2023-05-12 15:00
Thanks for the report!

**Comment by danyill** [comment] 2023-05-12 18:32
I think this is an indicator that overall system memory is becoming constrained - I'd suggest closing tabs or other applications which should free up memory to allow the validator to perform.

It's not (shouldn't be) related to ConductingEquipment specifically, more the overall size of the SCL file and the memory of the system. I occasionally have this problem when I have an application leaking memory. 

However I don't often try to use SCL files of 45 Mb which is about where performance starts to become an issue in OpenSCD at the moment (I tested with file of about 30 Mb from time to time).

**Comment by arulrajirudayasamy** [comment] 2023-05-12 19:56
@danyill Thanks for your feedback and I understand this is definitely related to the system memory.

I tried to monitor the memory usage from the task manager side by side, noticed that the CPU memory hits 100% all of the sudden that leads to the problem reported.

I tried to stop the unused services and closed all the other apps except running OpenSCD.
This unwanted error sometimes leads to crashing of OpenSCD,all of the sudden all the work done is disappeared and went in vain. 

This sometime demotivates the OpenSCD users.

I have one .SCD file that is around 600MB and I am not even able to open it in OpenSCD

**Comment by arulrajirudayasamy** [comment] 2023-05-12 20:00
I would appreciate the developer to provide the system requirements in the Wiki area for the better performance of OpenSCD

**Comment by Sander3003** [comment] 2023-05-15 09:29
How much Gb memory do you have in your computer?
Chrome supports upto maximal 256 Mb size.

You can send you error files to your collegues @microjacobon  for testing.

What brand of IED's are in the SCD files?

**Comment by Sander3003** [comment] 2023-05-15 09:32
Suggestions to fix this:
- Optimalisation of code
- Auto-save

**Comment by danyill** [comment] 2023-05-19 21:32
TIL that even if you have plenty of memory there must also be adequate disk space. I have a 32 Gb RAM system and I had about 5-8 Gb of memory free but the validator was failing. It was because I had poorly managed my spare disk space and it was very low (like 5 Mb!). Once I made more disk space available it behaved fine with, say, 40 IEDs.

**Comment by danyill** [comment] 2023-08-04 04:44
Without an example file or a specific use case I'm not sure this is actionable. @microjacobon do you have some comments or feedback on where the issue is here and whether it is reproducible?

**Comment by Sander3003** [comment] 2023-08-29 12:35
@arulrajirudayasamy is this solved now?

**Closed** 2023-09-13 10:55 UTC
Labels: Kind: Bug
