### ISSUE TITLE
Add 104 Addresses to existing DOI/DAI (CDC: WYE/DEL)

### ISSUE THREAD

**Issue by dlabordus** [openscd/open-scd#775] opened 2022-05-24 10:58 UTC
**Is your feature request related to a problem? Please describe.**
As a 104 Engineer I want to add Address Elements to a existing DOI/DAI which don't have Address Element yet. 
Support CDC Types, like WYE that will have SDI Elements with their own CDC to handle how to create one Address Element below a one DAI Element.

**Describe the solution you'd like**
Extend the existing logic to support the new CDC types from issue #698. After this issue DOI's with CDC like WYE can also be selected to add Address Elements. This means configuring which SDI need to be searched for and be handle like this is it own DOI.

**Comment by juancho0202** [comment] 2024-01-11 08:50
Closing as duplicate of #1390

**Closed by juancho0202** 2024-01-11 08:50 UTC
Labels: Kind: Enhancement
