### ISSUE TITLE
Update/create icons for the substation plugin

### ISSUE THREAD

**Issue by juancho0202** [openscd/open-scd#1229] opened 2023-04-05 14:33 UTC
**Is your feature request related to a problem? Please describe.**
As a user of OpenSCD, particularly of the Substation plugin, I want to have a clear way to differentiate in the screen at the root level which elements are Substations and which are Lines or Processes.

**Describe the solution you'd like**
I would like to see the elements `Substation`, `Line` and `Process` to appear in the Substation plugin with an icon similar to the one that for example the `PowerTransformer` elements have:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/843030/230112488-c182109e-8eaf-4593-b16a-dd358a48c094.png">

**Acceptance criteria**
- Add icons for the aforementioned elements in the Substation plugin
- - Find suitable icons agreed by the community for the three elements 
- Show the new Icons:
Substation icon: https://www.flaticon.com/free-icon/electric-factory_4882901?term=substation&page=1&position=2&origin=search&related_id=4882901
Line: https://www.flaticon.com/free-icon/power-line_125390
Process: https://www.flaticon.com/free-icon/process_2041633?term=process&page=1&position=25&origin=style&related_id=2041633
Comply with icon license critria

Background:
Technical approach: Copy paste the SVG of the linked icon in this issue and put it in the package/open-scd/src/icons/icons.ts folder.

**Comment by Sander3003** [comment] 2023-04-24 11:26
Suggestion for icons:
Line: https://www.flaticon.com/free-icon/power-line_125390
Process: https://www.flaticon.com/free-icon/process_2041633?term=process&page=1&position=25&origin=style&related_id=2041633

**Comment by Sander3003** [comment] 2023-09-01 06:20
The issue is still relevant, it can be fixed one day!

**Comment by juancho0202** [comment] 2023-12-06 09:47
Technical approach: Copy paste the SVG of the linked icon in this issue and put it in the  `package/open-scd/src/icons/icons.ts` folder.

**Comment by Sander3003** [comment] 2024-01-19 09:43
https://github.com/ca-d/oscd-designer/blob/main/icons.ts can be a source as well. This is in investigation.

**Comment by Sander3003** [comment] 2024-01-26 09:10
Investigation from Pascal: https://codepen.io/pascalwilbrink/full/gOEWKmy

**Comment by Sander3003** [comment] 2024-01-31 10:16
Powertransformer is theire:
![image](https://github.com/openscd/open-scd/assets/7427358/fb914862-fe55-4e23-958a-e6a8af2bc742)

**Comment by Sander3003** [comment] 2024-01-31 10:17
Winding is missing:
![image](https://github.com/openscd/open-scd/assets/7427358/35d9fee9-8364-41b1-9e19-ccd64580dd2b)

**Comment by Sander3003** [comment] 2024-01-31 10:26
Requests:

Reuse the substation icon already used in OpenSCD (no design needed)

Make a material design like icon's based on the following examples:


Bay:
![image](https://github.com/openscd/open-scd/assets/7427358/057920ec-340d-4559-8ca0-42afe3ccba82)

Voltage level:
![image](https://github.com/openscd/open-scd/assets/7427358/69bb05ce-7b6b-4abd-b45d-a2d9009f35d1)

Winding:
![image](https://github.com/openscd/open-scd/assets/7427358/4a68f525-5134-4c1b-a58c-44e041c0ddc1)


Proces:
https://www.flaticon.com/free-icon/process_2041633?term=process&page=1&position=25&origin=style&related_id=2041633

Line:
https://www.flaticon.com/free-icon/power-line_125390

**Comment by JakobVogelsang** [comment] 2024-02-07 10:51
Jan was so kind and offered to also take a look at our primary apparatus icons that are:

Circuit breaker:
<img width="48" alt="grafik" src="https://github.com/openscd/open-scd/assets/66802940/a92c9071-cfea-4b48-a57b-ecb7364a7daf">

disconnector:
<img width="48" alt="grafik" src="https://github.com/openscd/open-scd/assets/66802940/37e2aabc-9001-437c-b5fc-a8200e3ad47d">

Earth switch:
<img width="46" alt="grafik" src="https://github.com/openscd/open-scd/assets/66802940/ff436f9c-86eb-47cd-ae4b-e805e75ad867">

Current transformer:
<img width="53" alt="grafik" src="https://github.com/openscd/open-scd/assets/66802940/94c74382-f1c8-4171-8a04-4115736e4065">

Voltage transformer:
<img width="45" alt="grafik" src="https://github.com/openscd/open-scd/assets/66802940/0ec4d259-9fdf-41a2-9ede-00af16399dd5">


General primary apparatus:
<img width="73" alt="grafik" src="https://github.com/openscd/open-scd/assets/66802940/515e8da0-6f73-4466-a862-1b5ed3ecb1b1"> (I think this is material already but maybe Jan can think of a better one)

**Comment by JanDietvorst** [comment] 2024-03-12 09:43
Hi all,
Here are all the icons as shown above. I discussed everything with Jakob. If there is a need for more icons in the future please let me know. I'm happy to help!
J
![IC_Bay 24px](https://github.com/openscd/open-scd/assets/128469611/6cba35bd-d817-45b6-a537-df9f560daffa)
![IC_Bay 48px](https://github.com/openscd/open-scd/assets/128469611/02dbd15d-6876-4711-b52e-a9a43ab2f9e0)
![IC_Circuitbraker 24px](https://github.com/openscd/open-scd/assets/128469611/4ca2f27c-5258-4779-9b94-f3cf544a4346)
![IC_Circuitbraker 48px](https://github.com/openscd/open-scd/assets/128469611/3d4fadb9-8698-4eab-9361-52c18e696062)
![IC_Current transformer 24px](https://github.com/openscd/open-scd/assets/128469611/8ceb6b6a-0ae4-4cd0-9771-2f83fcfe1f2e)
![IC_Current transformer 48px](https://github.com/openscd/open-scd/assets/128469611/9c8baf55-2ce5-49b1-8d8f-6241c81ec679)
![IC_Disconnector 24px](https://github.com/openscd/open-scd/assets/128469611/512e9b06-c61f-4663-90a7-e05cc0221952)
![IC_Disconnector 48px](https://github.com/openscd/open-scd/assets/128469611/23362a0d-2812-4684-94c1-7bdbabf826b0)
![IC_Earth switch 24px](https://github.com/openscd/open-scd/assets/128469611/c893301b-cf19-4734-82bc-aa0c3c680bfd)
![IC_Earth switch 48px](https://github.com/openscd/open-scd/assets/128469611/0bc71822-452b-42ae-a829-8f9d3e7b5a86)
![IC_General primary aparatus 2C 24px](https://github.com/openscd/open-scd/assets/128469611/c754bc59-5e5f-4016-9eda-fdd5cf2ef596)
![IC_General primary aparatus 2C 48px](https://github.com/openscd/open-scd/assets/128469611/107831e9-9777-4375-bfbf-9a96e0f6570c)
![IC_General primary aparatus 3C 24px](https://github.com/openscd/open-scd/assets/128469611/ab873eae-e014-4372-9381-3a4d9f0752da)
![IC_General primary aparatus 3C 48px](https://github.com/openscd/open-scd/assets/128469611/4e294771-1b2e-4944-8ded-7482831514a3)
![IC_Line 24px](https://github.com/openscd/open-scd/assets/128469611/7abd9ae4-ebda-4114-81e3-0ff481089f8d)
![IC_Line 48px](https://github.com/openscd/open-scd/assets/128469611/9ddb079c-b9f2-46a8-a7d2-f05b61760be0)
![IC_Power transformer 24px](https://github.com/openscd/open-scd/assets/128469611/80f55efa-8fe4-4f4b-a2a4-912963ccab9a)
![IC_Power transformer 48px](https://github.com/openscd/open-scd/assets/128469611/e53aadde-c125-48b1-8995-8401ea4efa7d)
![IC_Powerline 24px](https://github.com/openscd/open-scd/assets/128469611/32eb4342-30d6-44ed-8cb1-bd7f1f561a33)
![IC_Powerline 48px](https://github.com/openscd/open-scd/assets/128469611/7eca21b5-1807-4820-bdb8-949b98cbce5b)
![IC_Process 24px](https://github.com/openscd/open-scd/assets/128469611/fcf8212c-3dcb-4791-9999-c9e19613c654)
![IC_Process 48px](https://github.com/openscd/open-scd/assets/128469611/da1c7bbb-a141-4955-a6c0-24891f44a319)
![IC_Substation 24px](https://github.com/openscd/open-scd/assets/128469611/fc59a1c4-736e-4110-b53b-d2877993aa42)
![IC_Substation 48px](https://github.com/openscd/open-scd/assets/128469611/96fcd41b-b824-4421-94bc-ed5bab83790f)
![IC_Voltage level 24px](https://github.com/openscd/open-scd/assets/128469611/815605b6-1958-432c-a992-cf4d3a3b2b20)
![IC_Voltage level 48px](https://github.com/openscd/open-scd/assets/128469611/011bb5e5-d153-4abe-9405-e9d551767fcf)
![IC_Voltage transformer 24px](https://github.com/openscd/open-scd/assets/128469611/4ab06c36-942e-4e6c-a3cc-f21fcc98223f)
![IC_Voltage transformer 48px](https://github.com/openscd/open-scd/assets/128469611/5dc4ae5a-8ba6-41e1-aa62-ad68531e9328)
![IC_Winding 24px](https://github.com/openscd/open-scd/assets/128469611/cbb6e9a9-396e-4cab-a192-8d3e7b833d30)
![IC_Winding 48px](https://github.com/openscd/open-scd/assets/128469611/43d110dd-023b-49ae-8ddc-7f8049696b0b)

**Comment by Sander3003** [comment] 2024-03-12 10:14
Thanks @JanDietvorst!

**Comment by juancho0202** [comment] 2024-03-19 08:43
Hey @JanDietvorst we would appreciate if you added the name of each icon and a short description of how they are meant to be used. Thanks!

**Comment by JanDietvorst** [comment] 2024-03-26 11:02
Hi @juancho0202 i've added the svg's of the icons above. The name of each svg contains the meaning of the icon. Also the use is in the name 24 or 48px.

**Comment by juancho0202** [comment] 2024-03-27 13:04
@Sander3003 we have decided during refinement that we will not use the IC_Powerline icon for the Line element but we'll stick with the IC_Line one. Also from the two options for general equipment we have chosen the 2C option.

**Closed** 2024-04-12 08:31 UTC
Labels: Kind: Enhancement
